services:
  backend:
    container_name: prj-backend
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - weaviate
      - postgres
    restart: unless-stopped
    extra_hosts:                # ⚡️ Thêm dòng này
      - "host.docker.internal:host-gateway"  # Cho phép backend gọi ra Windows host

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
  
  weaviate:
    image: semitechnologies/weaviate:1.32.2
    container_name: prj-weaviate
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: /var/lib/weaviate
      CLUSTER_HOSTNAME: prj-weaviate
    volumes:
      - weaviate-data:/var/lib/weaviate
    restart: unless-stopped

  postgres:
    image: postgres:17.6
    container_name: prj-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  weaviate-data:
    name: prj-weaviate-data
  postgres-data:
    name: prj-postgres-data
